Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompraVenta.Models
{
    public enum AnnouncementFilter
    {
        Title,
        Date,
        SellerUserName,
        ArticleName,
        ArticleCategory,
        ArticlePrice,
    }

    public class Announcement
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Date { get; set; }
        public int ArticleId { get; set; }
    }
}

ViewModels/AnnounceViewModel.cs
using CompraVenta.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CompraVenta.ViewModels
{
    public class AnnounceViewModel
    {
        public AnnounceViewModel()
        {
            ImagePath = "user.png";
            ImageFile = null;
        }
        public int Id { get; set; }

        public int ArticleId { get; set; }

        [Required]
        public string Title { get; set; }

        public string SellerId { get; set; }

        public string SellerUserName { get; set; }

        public DateTime Date { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Category { get; set; }

        [Required]
        [DataType(DataType.Duration)]
        public double Price { get; set; }

        public string Description { get; set; }

        public bool InCar { get; set; }

        public List<Comment> Comments { get; set; }

        public IFormFile ImageFile { get; set; }

        public string ImagePath { get; set; }

        public bool Sold { get; set; }

        public string Owner { get; set; }

        public ArticleCategory getCategory() => AnnounceViewModel.getCategory(Category);

        /******** Comment Form **************/
        public string CommentFormDescription { get; set; }

        public static ArticleCategory getCategory(string s)
        {
            switch (s.ToLower())
            {
                case "hogar":
                    return ArticleCategory.Hogar;
                case "autos":
                    return ArticleCategory.Autos;
                case "vivienda":
                    return ArticleCategory.Vivienda;
                case "electronico":
                    return ArticleCategory.Electronico;
                case "vestuario":
                    return ArticleCategory.Vestuario;
                case "all":
                    return ArticleCategory.All;
                default:
                    return ArticleCategory.Undefined;
            }
        }
    }
}

ViewModels/AnnouncementsViewModel.cs
using CompraVenta.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompraVenta.ViewModels
{
    public class AnnouncementsViewModel
    {
        public AnnouncementsViewModel()
        {
            MinPrice = double.MinValue;
            MaxPrice = double.MaxValue;
            Category = "All";
            SearchText = "";
        }
        public IEnumerable<AnnounceViewModel> Announcements { get; set; }
        public string SearchText{ get; set; }
        public string Category { get; set; }
        public double? MinPrice { get; set; }
        public double? MaxPrice { get; set; }

        public int Page { get; set; }
        public int TotalPages { get; set; }
        public string Seller { get; set; }
        public string State { get; set; }
        public int FirstAnnounceOnPage() => (Page - 1) * 5;
        public int LastAnnounceOnPage() => FirstAnnounceOnPage() + 4;
    }
}

Controllers/AnnouncementController.cs
using CompraVenta.Models;
using CompraVenta.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CompraVenta.Controllers
{
    [Authorize(Roles = "Client,Admin")]
    public class AnnouncementController : Controller
    {
        private readonly AppDbContext context;
        private readonly IHostingEnvironment hostingEnvironment;

        public AnnouncementController(AppDbContext context,
                                        IHostingEnvironment hostingEnvironment)
        {
            this.context = context;
            this.hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Announcements(double? maxPrice, double? minPrice, string searchText = "", string category = "", int page = 1, string seller = "", string state = "All")
        {
            var announcements = from announcement in context.Announcements
                                join article in context.Articles on announcement.ArticleId equals article.Id
                                select new AnnounceViewModel
                                {
                                    Id = announcement.Id,
                                    ArticleId = article.Id,
                                    Title = announcement.Title,
                                    SellerUserName = article.SellerUserName,
                                    Date = announcement.Date,
                                    Name = article.Name,
                                    Category = article.Category.ToString(),
                                    Price = article.Price,
                                    Description = article.Description,
                                    Sold = article.Sold,
                                    Owner = article.Owner,
                                };
            // Filter by category
            if (!string.IsNullOrEmpty(category) && category.ToLower() != "all")
            {
                announcements = announcements.Where(e => e.getCategory() == AnnounceViewModel.getCategory(category));
            }
            // Filter by price
            if (minPrice != null)
            {
                announcements = announcements.Where(e => e.Price >= minPrice);
            }
            if (maxPrice != null)
            {
                announcements = announcements.Where(e => e.Price <= maxPrice);
            }
            // Filter by text
            if (!string.IsNullOrEmpty(searchText))
            {
                announcements = announcements.Where(e => 
                                                    e.Description.Contains(searchText, StringComparison.CurrentCultureIgnoreCase)
                                                    || e.Title.Contains(searchText, StringComparison.CurrentCultureIgnoreCase)
                                                    || e.SellerUserName.Contains(searchText, StringComparison.CurrentCultureIgnoreCase)
                                                    );
            }
            if (!string.IsNullOrEmpty(seller))
            {
                announcements = announcements.Where(e => e.SellerUserName.Equals(seller));
            }
            if (!User.IsInRole("Admin"))
            {
                announcements = announcements.Where(e => !e.Sold);

            }
            else
            {
                if (state.ToLower() == "free")
                {
                    announcements = announcements.Where(e => !e.Sold);
                }
                else if (state.ToLower() == "sold")
                {
                    announcements = announcements.Where(e => e.Sold);
                }
            }

            int amount = announcements.Count();

            announcements = announcements.OrderByDescending(e => e.Date).Skip(4 * (page - 1)).Take(4);

            return View(new AnnouncementsViewModel
            {
                Announcements = announcements,
                Page = page,
                SearchText = searchText,
                MinPrice = minPrice,
                MaxPrice = maxPrice,
                Category = category,
                TotalPages = (int)Math.Ceiling((decimal)amount / 4),
                Seller = seller,
                State = state
            });
        }

        [HttpGet]
        public IActionResult Announce() => View();

        [HttpPost]
        public IActionResult Announce(AnnounceViewModel model)
        {
            var date = DateTime.Now;
            if (ModelState.IsValid)
            {

                string uniqueFileName = null;
                if (model.ImageFile != null)
                {
                    uniqueFileName = Utils.FileProcess.UploadFile(model.ImageFile, hostingEnvironment);
                }

                var article = new Article
                {
                    Name = model.Name,
                    Category = model.getCategory(),
                    Price = model.Price,
                    Description = model.Description,
                    SellerUserName = User.Identity.Name,
                    ImageFilePath = uniqueFileName,
                };
                context.Articles.Add(article);
                context.SaveChanges();
                var announcement = new Announcement
                {
                    Title = model.Title,
                    Date = date,
                    ArticleId = article.Id,
                };
                context.Announcements.Add(announcement);
                context.SaveChanges();
                return RedirectToAction("Announcements");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult AnnouncementDetails(int? id)
        {
            var announcement = context.Announcements.FirstOrDefault(e => e.Id.Equals(id));
            var article_ = context.Articles.FirstOrDefault(e => e.Id.Equals(announcement.ArticleId));
            var comments = context.Comments.Where(e => e.AnnouncementId.Equals(id)).OrderByDescending(e => e.PubDate);

            var userArticles = from userArticle in context.ShoppingCar
                               join article in context.Articles on userArticle.ArticleId equals article.Id
                               select new
                               {
                                   article.Id,
                                   article.Name,
                                   article.Price,
                                   article.Category,
                                   userArticle.UserName,
                                   article.SellerUserName
                               };
            userArticles = userArticles.Where(e => e.UserName.Equals(User.Identity.Name));

            bool inCar = userArticles.FirstOrDefault(e => e.Id.Equals(id)) != null;

            var obj = new AnnounceViewModel
            {
                Id = announcement.Id,
                ArticleId = article_.Id,
                Title = announcement.Title,
                Date = announcement.Date,
                Name = article_.Name,
                SellerUserName = article_.SellerUserName,
                Category = article_.Category.ToString(),
                Description = article_.Description,
                Price = article_.Price,
                Comments = comments.ToList(),
                ImagePath = article_.ImageFilePath,
                InCar = inCar,
                Sold = article_.Sold,
                Owner = article_.Owner
            };
            return View(obj);
        }

        [HttpPost]
        public IActionResult Remove(int id, int articleId)
        {
            var announcement = context.Announcements.FirstOrDefault(e => e.Id.Equals(id));
            var article = context.Articles.FirstOrDefault(e => e.Id.Equals(articleId));

            if (announcement == null || article == null)
            {
                return RedirectToAction("NotFound");
            }

            context.Announcements.Remove(announcement);
            context.Articles.Remove(article);
            context.SaveChanges();

            return RedirectToAction("Announcements");
        }

        [HttpPost]
        public IActionResult AnnouncementDetails(AnnounceViewModel model)
        {
            var date = DateTime.Now;
            var comment = new Comment
            {
                Description = model.CommentFormDescription,
                UserId = User.Identity.Name,
                PubDate = date,
                AnnouncementId = model.Id,
            };
            context.Comments.Add(comment);
            context.SaveChanges();
            return RedirectToAction("AnnouncementDetails", model.Id);
        }
    }
}

Views/Announcement/Announce.cshtml
@model CompraVenta.ViewModels.AnnounceViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wrapper-main">
    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3"> Anunciar </h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div class="contact-main">
        <div class="container">
            <!-- Content Row -->
            <div class="row">
                <!-- Map Column -->
                <div class="col-lg-8 mb-4 contact-left">
                    <h3> Rellene el formulario </h3>
                    <form method="post" enctype="multipart/form-data">
                        <div asp-validation-summary="All" class="text-danger"></div>

                        <input type="hidden" asp-for="ImagePath" />

                        <div class="control-group form-group">
                            <div class="custom-file">
                                <input type="file" class="form-control custom-file-input" asp-for="ImageFile" style="margin-top: 0" />
                                <label class="custom-file-label">Inserte una imagen</label>
                            </div>
                        </div>

                        <div class="control-group form-group">
                            <div class="controls">
                                <input asp-for="Title" type="text" placeholder="Título del anuncio" class="form-control" id="title" required data-validation-required-message="Entre el título del artículo.">
                                <p class="help-block"></p>
                            </div>
                        </div>

                        <select class="control-group form-group browser-default custom-select" asp-for="Category">
                            <option selected disabled>Categoría</option>
                            <option value="Hogar">Hogar</option>
                            <option value="Electronico">Electrónico</option>
                            <option value="Vivienda">Vivienda</option>
                            <option value="Autos">Autos</option>
                            <option value="Vestuario">Vestuario</option>
                        </select>

                        <div class="control-group form-group">
                            <div class="controls">
                                <input asp-for="Name" type="text" placeholder="Nombre del artículo" class="form-control" id="name" required data-validation-required-message="Entre el nombre del artículo.">
                                <p class="help-block"></p>
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <input asp-for="Price" type="number" placeholder="Precio del Artículo" class="form-control" id="price" required data-validation-required-message="Especifique el precio del artículo.">
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <textarea asp-for="Description" rows="10" cols="100" placeholder="Detalles" class="form-control" id="message" maxlength="999" style="resize:none"></textarea>
                            </div>
                        </div>
                        <div id="success"></div>
                        <!-- For success/fail messages -->
                        <button type="submit" class="btn btn-primary" id="sendMessageButton">Publicar</button>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.custom-file-input').on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).next('.custom-file-label').html(fileName);
        });
    });
</script>

Views/Announcement/AnnouncementDetails.cshtml
@using CompraVenta.ViewModels;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<Account> SignInManager
@model AnnounceViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string imageFile = Model.ImagePath ?? "user.png";
}
<div class="wrapper-main">
    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3"> Anuncio </h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div class="blog-main">
        <div class="container">
            <div class="row">
                <!-- Post Content Column -->
                <div class="col-lg-8">
                    <!-- Title -->
                    <h1 class="text-center"><strong>@Model.Title</strong></h1>
                    <h2 class="text-center">@Model.Name</h2>
                    <h3 class="text-left text-secondary my-4">Categoría: @Model.Category.</h3>
                    <h5 class="text-center">por <a asp-action="AccountDetails" asp-controller="Account" asp-route-userName="@Model.SellerUserName">@Model.SellerUserName</a></h5>

                    <div class="container text-center">
                        <img class="img-fluid" src="~/images/@imageFile" alt="" width="70%" />
                    </div>

                    <hr>
                    <!-- Date/Time -->
                    <p class="text-black-50">Publicado el @Model.Date</p>
                    <hr>
                    <h3 class="text-left">Precio: $@Model.Price</h3>
                    <!-- Post Content -->
                    <h2 class="text-center">Detalles:</h2>
                    <p>@Model.Description</p>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        if (Model.Sold)
                        {
                            <h5 class="btn-outline-warning">Vendido a <a asp-action="AccountDetails" asp-controller="Account" asp-route-username="@Model.Owner">@Model.Owner</a></h5>
                        }
                        else if (Model.SellerUserName != User.Identity.Name)
                        {
                            @if (!Model.InCar)
                            {
                                <form method="post" asp-action="AddToCar" asp-controller="ShoppingCar" asp-route-articleId="@Model.ArticleId" asp-route-username="@User.Identity.Name">
                                    <button class="btn btn-primary" type="submit">Añadir al carrito</button>
                                </form>
                            }
                            else
                            {
                                <h5 class="btn btn-success">En el carrito</h5>
                            }
                        }
                        else
                        {
                            <form method="post" asp-action="Remove" asp-controller="Announcement" asp-route-id="@Model.Id" asp-route-articleId="@Model.ArticleId">
                                <button class="btn btn-danger" type="submit">Eliminar</button>
                            </form>
                        }

                        <div class="blog-right-side">
                            <!-- Comments Form -->
                            <div class="card my-4">
                                <h5 class="card-header">Deje su comentario:</h5>
                                <div class="card-body">
                                    <form method="post">
                                        <div asp-validation-summary="All" class="text-danger"></div>
                                        <div class="form-group">
                                            <textarea asp-for="CommentFormDescription" class="form-control" rows="3"></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Comentar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }

                    @foreach (var comment in Model.Comments)
                    {
                        <div class="media mb-4">
                            <img class="d-flex mr-3 rounded-circle" src="images/testi_03.png" alt="">
                            <div class="media-body">
                                <h5 class="mt-0"><a asp-action="AccountDetails" asp-controller="Account" asp-route-userName="@comment.UserId">@comment.UserId</a></h5>
                                <p>@comment.Description</p>
                                Publicado el @comment.PubDate
                                <hr />
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

Views/Announcement/Announcements.cshtml
@using Microsoft.AspNetCore.Identity;
@using CompraVenta.ViewModels;
@inject SignInManager<Account> SignInManager
@model AnnouncementsViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = string.IsNullOrEmpty(Model.Seller) ? "Anuncios" : "Anuncios de " + Model.Seller;
}
<div class="wrapper-main">
    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3">@title</h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div class="blog-main">
        <div class="container">
            <div class="row">
                <!-- Blog Entries Column -->
                <div class="col-md-8 blog-entries">
                    @{ 
                        int it = 0;
                    }
                    @foreach (var announce in Model.Announcements)
                    {
                        it++;
                        <!-- Blog Post -->
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="by-post">
                                    Publicado el @announce.Date por <a asp-action="AccountDetails" asp-controller="Account" asp-route-userName="@announce.SellerUserName">@announce.SellerUserName</a>.
                                </div>
                                <h2 class="card-title">@announce.Title</h2>
                                @{
                                    string Summary;
                                    if (announce.Description.Length > 30)
                                    {
                                        int len = Math.Min(150, announce.Description.Length);
                                        Summary = announce.Description.Substring(0, len) + "...";
                                    }
                                    else
                                    {
                                        Summary = announce.Description;
                                    }
                                }
                                <p class="card-text">@Summary</p>
                                <h5 class="card-title">Precio: $@announce.Price</h5>
                                @if (announce.Sold)
                                {
                                    <h5 class="btn-outline-warning">Vendido a <a asp-action="AccountDetails" asp-controller="Account" asp-route-username="@announce.Owner">@announce.Owner</a></h5>
                                }
                                <a asp-action="AnnouncementDetails" asp-route-id="@announce.Id" asp-controller="Announcement" class="btn btn-primary">
                                    Saber más &rarr;
                                </a>
                            </div>
                        </div>
                    }
                    <div class="pagination_bar_arrow">
                        <!-- Pagination -->
                        <ul class="pagination justify-content-center mb-4">
                            <li class="page-item">
                                @{ 
                                    int prev = Model.Page - 1;
                                    int next = Model.Page + 1;
                                }
                                @if (Model.Page <= 1)
                                {
                                    <a class="page-link disabled">&larr; Older</a>
                                }
                                else
                                {
                                    <a class="page-link" asp-action="Announcements" asp-controller="Announcement" 
                                       asp-route-page="@prev"
                                       asp-route-searchText="@Model.SearchText"
                                       asp-route-minPrice="@Model.MinPrice"
                                       asp-route-maxPrice="@Model.MaxPrice"
                                       asp-route-category="@Model.Category"
                                       asp-route-seller="@Model.Seller"
                                       asp-route-state="@Model.State"
                                    >&larr; Older</a>
                                }
                            </li>
                            <li class="page-item">
                                @if (Model.Page >= Model.TotalPages)
                                {
                                    <a class="page-link disabled">Newer &rarr;</a>
                                }
                                else
                                {
                                    <a class="page-link" asp-action="Announcements" asp-controller="Announcement" 
                                       asp-route-page="@next"
                                       asp-route-searchText="@Model.SearchText"
                                       asp-route-minPrice="@Model.MinPrice"
                                       asp-route-maxPrice="@Model.MaxPrice"
                                       asp-route-category="@Model.Category"
                                       asp-route-seller="@Model.Seller"
                                       asp-route-state="@Model.State"
                                    >&rarr; Newer</a>
                                }
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Sidebar Widgets Column -->
                <div class="col-md-4 blog-right-side">
                    <!-- Search Widget -->
                    <form method="get" asp-action="Announcements" asp-controller="Announcement" class="card my-4">
                        <h5 class="card-header">Buscar:</h5>
                        <input type="text" hidden asp-for="Seller" />
                        <input type="text" hidden asp-for="Page" value="1" />

                        <div class="card my-4">
                            <div class="card-body">
                                <div class="input-group">
                                    <input type="text" asp-for="SearchText" value="@Model.SearchText" class="form-control" placeholder="Texto...">
                                </div>
                            </div>
                        </div>

                        <div class="card my-4">
                            <h5 class="card-header">Categorías:</h5>
                            <select class="control-group form-group-lg browser-default custom-select-lg" asp-for="Category">
                                <option class="custom-select-lg" value="All" selected>Todos</option>
                                <option class="custom-select-lg" value="Hogar">Hogar</option>
                                <option class="custom-select-lg" value="Electronico">Electrónico</option>
                                <option class="custom-select-lg" value="Vivienda">Vivienda</option>
                                <option class="custom-select-lg" value="Autos">Autos</option>
                                <option class="custom-select-lg" value="Vestuario">Vestuario</option>
                            </select>
                        </div>

                        @if (User.IsInRole("Admin"))
                        {
                            <div class="card my-4">
                                <h5 class="card-header">Estado:</h5>
                                <select class="control-group form-group-lg browser-default custom-select-lg" asp-for="State">
                                    <option class="custom-select-lg" value="All">Todos</option>
                                    <option class="custom-select-lg" value="Free">En venta</option>
                                    <option class="custom-select-lg" value="Sold">Comprados</option>
                                </select>
                            </div>
                        }

                        <div class="card my-4">
                            <h5 class="card-header">Rango de Precios:</h5>
                            <div class="card-body">
                                <div class="row my-2">
                                    <h3 class="col-lg-4">Max:</h3>
                                    <div class="col-lg-8">
                                        <input asp-for="MaxPrice" class="form-control" type="number" />
                                    </div>
                                </div>
                                <div class="row my-2">
                                    <h3 class="col-lg-4">Min:</h3>
                                    <div class="col-lg-8">
                                        <input asp-for="MinPrice" class="form-control" type="number" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Filtrar</button>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </div>
</div>