Models/ShoppingCar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompraVenta.Models
{
    public class ShoppingCar
    {
        public int Id { get; set; }

        public string UserName{ get; set; }

        public int ArticleId { get; set; }
    }
}

ViewModels/ShoppingCarViewModel.cs
using CompraVenta.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompraVenta.ViewModels
{
    public class ShoppingCarViewModel
    {
        public string UserName { get; set; }
        public List<Article> Articles { get; set; }
        public double TotalPrice { get; set; }
    }
}

Controllers/ShoppingCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CompraVenta.Models;
using CompraVenta.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CompraVenta.Controllers
{
    [Authorize(Roles = "Admin,Client")]
    public class ShoppingCarController : Controller
    {
        private readonly UserManager<Account> userManager;
        private readonly SignInManager<Account> signInManager;
        private readonly AppDbContext context;

        public ShoppingCarController(UserManager<Account> userManager,
                                SignInManager<Account> signInManager,
                                AppDbContext context)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.context = context;
        }

        [HttpGet]
        public IActionResult Details(string username)
        {
            var userArticles = from userArticle in context.ShoppingCar
                         join article in context.Articles on userArticle.ArticleId equals article.Id
                         select new
                         {
                             article.Id,
                             article.Name,
                             article.Price,
                             article.Category,
                             userArticle.UserName,
                             article.SellerUserName,
                             article.Sold
                         };
            userArticles = userArticles.Where(e => e.UserName.Equals(username));

            double totalPrice = userArticles.Sum(e => e.Sold ? 0 : e.Price);

            List<Article> articles = new List<Article>();

            foreach (var article in userArticles)
            {
                articles.Add(new Article
                {
                    Id = article.Id,
                    Category = article.Category,
                    Name = article.Name,
                    Price = article.Price,
                    SellerUserName = article.SellerUserName,
                    Sold = article.Sold
                });
            }

            return View(new ShoppingCarViewModel
            {
                UserName = username,
                TotalPrice = totalPrice,
                Articles = articles
            });
        }

        [HttpPost]
        public IActionResult AddToCar(int articleId, string username)
        {
            // check if item is in car
            var userArticles = from userArticle in context.ShoppingCar
                               join article in context.Articles on userArticle.ArticleId equals article.Id
                               select new
                               {
                                   article.Id,
                                   article.Name,
                                   article.Price,
                                   article.Category,
                                   userArticle.UserName,
                                   article.SellerUserName
                               };
            userArticles = userArticles.Where(e => e.UserName.Equals(username));

            if (userArticles.FirstOrDefault(e => e.Id.Equals(articleId)) != null || !User.Identity.Name.Equals(username))
            {
                return View("NotFound");
            }

            var article_ = context.Articles.FirstOrDefault(e => e.Id.Equals(articleId));

            if (article_.Sold)
            {
                return RedirectToAction("Announcements", "Announcement");
            }

            if (article_ == null)
            {
                return View("NotFound");
            }

            context.ShoppingCar.Add(new ShoppingCar
            {
                ArticleId = articleId,
                UserName = username
            });

            context.SaveChanges();

            return RedirectToAction("Details", new { username });
        }

        [HttpPost]
        public IActionResult RemoveFromCar(int? articleId)
        {
            string username = User.Identity.Name;
            var result = context.ShoppingCar.FirstOrDefault(e => e.ArticleId.Equals(articleId) && e.UserName.Equals(username));
            var article = context.Articles.FirstOrDefault(e => e.Id.Equals(articleId));

            if (articleId == null || result == null)
            {
                return View("NotFound");
            }

            context.ShoppingCar.Remove(result);

            context.SaveChanges();

            return RedirectToAction("Details", new { username });
        }

        [HttpGet]
        public IActionResult BuyAll()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BuyAll(string username)
        {
            var query = from userArticle in context.ShoppingCar
                               join article in context.Articles on userArticle.ArticleId equals article.Id
                               select new
                               {
                                   article.Id,
                                   article.Name,
                                   article.Price,
                                   article.Category,
                                   userArticle.UserName,
                                   article.SellerUserName,
                                   article.Sold,
                                   article.Owner
                               };

            query = query.Where(e => e.UserName.Equals(username) && !e.Sold);

            List<int> Ids = new List<int>();

            query.ToList().ForEach(e => Ids.Add(e.Id));

            var articles = context.Articles.Where(e => Ids.Contains(e.Id));

            foreach (var article in articles)
            {
                article.Sold = true;
                article.Owner = username;
            }

            context.ShoppingCar.RemoveRange(context.ShoppingCar.Where(e => e.UserName.Equals(username) && Ids.Contains(e.ArticleId)));

            context.SaveChanges();

            return RedirectToAction("Details", new { username });
        }
    }
}

Views/ShoppingCar/BuyAll.cshtml
@using CompraVenta.ViewModels;
@using Microsoft.AspNetCore.Identity;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="contact-main">
    <div class="container">
        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div class="col-lg-8 mt-4 contact-left">
                <h3>Introduzca los datos de su tarjeta para efectuar la compra</h3>

                <form method="post" class="my-5">
                    <div class="control-group form-group">
                        <input type="text" class="form-control" placeholder="dirección de envío" />
                    </div>
                    <div class="control-group form-group">
                        <input type="number" class="form-control" placeholder="número de tarjeta" />
                    </div>
                    <div class="control-group form-group">
                        <input type="password" class="form-control" placeholder="PIN" />
                    </div>

                    <button type="submit" class="btn btn-success mt-2" asp-action="BuyAll" asp-controller="ShoppingCar" asp-route-username="@User.Identity.Name">Comprar</button>
                </form>

            </div>
        </div>
    </div>
</div>

Views/ShoppingCar/Details.cshtml
@using CompraVenta.ViewModels;
@model ShoppingCarViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="wrapper-main">
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3"> Carro de Compras </h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div class="blog-main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-entries">
                    <h4>Tienes @Model.Articles.Count  Artículo(s) en el carrito</h4>
                    <hr />
                    <h5 class="my-4"><strong>Precio total: </strong> @Model.TotalPrice </h5>
                    <hr />

                    @foreach (var article in Model.Articles)
                    {
                        <div class="card mb4 my-4">
                            <div class="card-body">
                                @if (article.Sold)
                                {
                                    <h5 class="btn-warning">No disponible</h5>
                                }
                                <h2 class="card-title"><a asp-action="AnnouncementDetails" asp-controller="Announcement" asp-route-id="@article.Id">@article.Name</a></h2>
                                
                                <h6 class="card-title my-4">Precio: @article.Price</h6>
                                
                                <h5 class="card-subtitle">Vendedor: <a asp-action="AccountDetails" asp-controller="Account" asp-route-username="@article.SellerUserName">@article.SellerUserName</a></h5>
                            </div>

                            <div class="card card-footer">
                                <form method="post">
                                    <button type="submit" class="btn btn-danger mt-2" asp-action="RemoveFromCar" asp-controller="ShoppingCar" asp-route-articleId="@article.Id">Eliminar del carrito</button>
                                </form>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                @if (Model.Articles.Count() > 0)
                {
                    <div class="col-md-8 blog-entries">
                        <a class="btn btn-success" asp-action="BuyAll" asp-controller="ShoppingCar">Comprar todo</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>